# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Compile\ui-py\client_search.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from DataBaseFunctions.db_connection import DB_Connect
from AppWidgets.SearchClient.clientActivityFrame import ScrollaAreaFrame


class SearchClient(QtWidgets.QWidget):
    def __init__(self, Main_TabWidget, Status_Label, parent=None):
        QtWidgets.QWidget.__init__(self, parent=parent)
        self.Main_TabWidget = Main_TabWidget
        self.Status_Label = Status_Label

        self.frames = []

    def search_client_form(self):
        def counter_cl_name_letters():
            try:
                if len(self.client_name_add_LineEdit.text()) > 30 or self.client_name_add_LineEdit.text()[-1].isdigit():
                    self.client_name_add_LineEdit.setText(self.client_name_add_LineEdit.text()[:-1])
                self.client_name_letter_num_Label.setText(str(len(self.client_name_add_LineEdit.text())))
            except IndexError:
                pass

        def counter_cl_secname_letters():
            try:
                if len(self.client_secname_add_LineEdit.text()) > 30 or self.client_secname_add_LineEdit.text()[-1].isdigit():
                    self.client_secname_add_LineEdit.setText(self.client_secname_add_LineEdit.text()[:-1])
                self.client_secname_letter_num_Label.setText(str(len(self.client_secname_add_LineEdit.text())))
            except IndexError:
                pass

        def counter_cl_fathername_letters():
            try:
                if len(self.client_fathername_add_LineEdit.text()) > 30 or self.client_fathername_add_LineEdit.text()[-1].isdigit():
                    self.client_fathername_add_LineEdit.setText(self.client_fathername_add_LineEdit.text()[:-1])
                self.client_fathername_letter_num_Label.setText(str(len(self.client_fathername_add_LineEdit.text())))
            except IndexError:
                pass

        def ClickSearch():
            connection = DB_Connect()
            line_edit_Error_style_sheet = "color: red"
            line_edit_Default_style_sheet = "color: black"
            client_information = []
            order_correct = True
            # Проверка наличия имени в строке имени клиента
            if self.client_name_add_LineEdit.text() == '':
                self.client_name_add_Label.setStyleSheet(line_edit_Error_style_sheet)
                order_correct = False
            else:
                self.client_name_add_Label.setStyleSheet(line_edit_Default_style_sheet)
                client_information.append(self.client_name_add_LineEdit.text().lower())

            # Проверка наличия фамилии в строке фамилии клиента
            if self.client_secname_add_LineEdit.text() == '':
                self.client_secname_add_Label.setStyleSheet(line_edit_Error_style_sheet)
                order_correct = False
            else:
                self.client_secname_add_Label.setStyleSheet(line_edit_Default_style_sheet)
                client_information.append(self.client_secname_add_LineEdit.text().lower())

            # Проверка наличия отчества в строке отчества клиента
            if self.client_fathername_add_LineEdit.text() == '':
                self.client_fathername_add_Label.setStyleSheet(line_edit_Error_style_sheet)
                order_correct = False
            else:
                self.client_fathername_add_Label.setStyleSheet(line_edit_Default_style_sheet)
                client_information.append(self.client_fathername_add_LineEdit.text().lower())

            if order_correct:
                print(client_information)
                client_activites_info = connection.search_client(client_information)
                if len(client_activites_info) != 0:
                    self.cl_found_name_LineEdit.setText(client_information[0])
                    self.cl_found_secname_LineEdit.setText(client_information[1])
                    self.cl_found_fathername_LineEdit.setText(client_information[2])
                    self.cl_activities_num_LineEdit.setText(str(len(client_activites_info)))


                    # Добавление новых фреймов в ScrollArea
                    for activity_info in client_activites_info:
                        FrameClass = ScrollaAreaFrame(self.verticalLayout_3, self.scrollAreaWidgetContents, activity_info)
                        new_frame = FrameClass.new_activity_frame()
                        self.verticalLayout_3.addWidget(new_frame)  # Layout от scrollArea

                    self.scroll_area_FrameSpacer = QtWidgets.QFrame(self.scrollAreaWidgetContents)
                    self.scroll_area_FrameSpacer.setObjectName("scroll_area_FrameSpacer")
                    self.verticalLayout_3.addWidget(self.scroll_area_FrameSpacer)

                    self.client_name_add_LineEdit.setText('')
                    self.client_secname_add_LineEdit.setText('')
                    self.client_fathername_add_LineEdit.setText('')

                else:
                    self.cl_found_name_LineEdit.setText("Ничего")
                    self.cl_found_secname_LineEdit.setText("не")
                    self.cl_found_fathername_LineEdit.setText("найдено")
                    self.cl_activities_num_LineEdit.setText("")

            connection.close_conn()


        def clickCloseTab():
            self.Main_TabWidget.removeTab(self.Main_TabWidget.indexOf(self.tab))


        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tab.setStyleSheet("QLabel{"
                               "font-family: \"Bahnschrift SemiBold\";"
                               "font-size: 15px;"
                               "color: rgb(75, 75, 75)}"
                               ""
                               "QLineEdit{"
                               "border-radius: 8px; "
                               "border: 1px solid #C7C7C7; "
                               "background-color:white;"
                               "font-family: \"Bahnschrift SemiBold\";"
                               "font-size: 17px;}"
                               ""
                               "QPushButton{border-radius: 8px; "
                               "border: 1px solid #C7C7C7; "
                               "background-color:white;"
                               "font-family: \"Bahnschrift SemiBold\";"
                               "font-size: 17px;}"
                               ""
                               "QPushButton:hover{"
                               "background-color:rgb(221, 221, 221);}"
                               "QPushButton:pressed{"
                               "background-color:rgb(156, 156, 156);"
                               "color:rgb(241, 241, 241)}"
                               ""
                               "QPushButton{border-radius: 8px; "
                               "border: 1px solid #C7C7C7; "
                               "background-color:white;"
                               "font-family: \"Bahnschrift SemiBold\";"
                               "font-size: 14px;}"
                               ""
                               "QPushButton:hover{"
                               "background-color:rgb(221, 221, 221);}"
                               "QPushButton:pressed{"
                               "background-color:rgb(156, 156, 156);"
                               "color:rgb(241, 241, 241)}"
                               )
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tab_title_Label = QtWidgets.QLabel(self.tab)
        self.tab_title_Label.setMinimumSize(QtCore.QSize(0, 36))
        self.tab_title_Label.setMaximumSize(QtCore.QSize(16777215, 90))
        self.tab_title_Label.setStyleSheet("background-color: rgba(169, 169, 169, 60);"
                                           "border-radius: 15px;"
                                           "font-size: 20px;"
                                           "color: black")
        self.tab_title_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.tab_title_Label.setObjectName("tab_title_Label")
        self.tab_title_Label.setText("Поиск Юр. лица")
        self.verticalLayout_2.addWidget(self.tab_title_Label)
        self.user_info_Frame = QtWidgets.QFrame(self.tab)
        self.user_info_Frame.setObjectName("user_info_Frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.user_info_Frame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.client_fathername_add_Frame = QtWidgets.QFrame(self.user_info_Frame)
        self.client_fathername_add_Frame.setMinimumSize(QtCore.QSize(0, 0))
        self.client_fathername_add_Frame.setMaximumSize(QtCore.QSize(570, 63))
        self.client_fathername_add_Frame.setObjectName("client_fathername_add_Frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.client_fathername_add_Frame)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(5)
        self.gridLayout_8.setVerticalSpacing(2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.client_name_add_Frame = QtWidgets.QFrame(self.user_info_Frame)
        self.client_name_add_Frame.setMaximumSize(QtCore.QSize(570, 63))
        self.client_name_add_Frame.setObjectName("client_name_add_Frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.client_name_add_Frame)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(3)
        self.gridLayout_6.setVerticalSpacing(2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.client_name_add_Label = QtWidgets.QLabel(self.client_name_add_Frame)
        self.client_name_add_Label.setMinimumSize(QtCore.QSize(0, 20))
        self.client_name_add_Label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.client_name_add_Label.setObjectName("client_name_add_Label")
        self.client_name_add_Label.setText("Имя")
        self.gridLayout_6.addWidget(self.client_name_add_Label, 0, 0, 1, 1)
        self.client_name_add_LineEdit = QtWidgets.QLineEdit(self.client_name_add_Frame)
        self.client_name_add_LineEdit.setMinimumSize(QtCore.QSize(300, 30))
        self.client_name_add_LineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.client_name_add_LineEdit.setObjectName("client_name_add_LineEdit")
        self.client_name_add_LineEdit.textChanged.connect(counter_cl_name_letters)
        self.gridLayout_6.addWidget(self.client_name_add_LineEdit, 1, 0, 1, 1)
        self.client_name_letter_num_Label = QtWidgets.QLabel(self.client_name_add_Frame)
        self.client_name_letter_num_Label.setMinimumSize(QtCore.QSize(40, 30))
        self.client_name_letter_num_Label.setMaximumSize(QtCore.QSize(40, 30))
        self.client_name_letter_num_Label.setObjectName("client_name_letter_num_Label")
        self.client_name_letter_num_Label.setText("0")
        self.gridLayout_6.addWidget(self.client_name_letter_num_Label, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.client_name_add_Frame, 0, 0, 1, 1)
        self.cleient_secname_add_Frame = QtWidgets.QFrame(self.user_info_Frame)
        self.cleient_secname_add_Frame.setMinimumSize(QtCore.QSize(0, 0))
        self.cleient_secname_add_Frame.setMaximumSize(QtCore.QSize(570, 63))
        self.cleient_secname_add_Frame.setObjectName("cleient_secname_add_Frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.cleient_secname_add_Frame)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(5)
        self.gridLayout_7.setVerticalSpacing(2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.client_secname_add_LineEdit = QtWidgets.QLineEdit(self.cleient_secname_add_Frame)
        self.client_secname_add_LineEdit.setMinimumSize(QtCore.QSize(300, 30))
        self.client_secname_add_LineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.client_secname_add_LineEdit.setObjectName("client_secname_add_LineEdit")
        self.client_secname_add_LineEdit.textChanged.connect(counter_cl_secname_letters)
        self.gridLayout_7.addWidget(self.client_secname_add_LineEdit, 1, 0, 1, 1)
        self.client_secname_add_Label = QtWidgets.QLabel(self.cleient_secname_add_Frame)
        self.client_secname_add_Label.setMinimumSize(QtCore.QSize(0, 20))
        self.client_secname_add_Label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.client_secname_add_Label.setObjectName("client_secname_add_Label")
        self.client_secname_add_Label.setText("Фамилия")
        self.gridLayout_7.addWidget(self.client_secname_add_Label, 0, 0, 1, 1)
        self.client_secname_letter_num_Label = QtWidgets.QLabel(self.cleient_secname_add_Frame)
        self.client_secname_letter_num_Label.setMinimumSize(QtCore.QSize(40, 30))
        self.client_secname_letter_num_Label.setMaximumSize(QtCore.QSize(40, 30))
        self.client_secname_letter_num_Label.setObjectName("client_secname_letter_num_Label")
        self.client_secname_letter_num_Label.setText("0")
        self.gridLayout_7.addWidget(self.client_secname_letter_num_Label, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.cleient_secname_add_Frame, 1, 0, 1, 1)
        self.client_fathername_add_LineEdit = QtWidgets.QLineEdit(self.client_fathername_add_Frame)
        self.client_fathername_add_LineEdit.setMinimumSize(QtCore.QSize(300, 30))
        self.client_fathername_add_LineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.client_fathername_add_LineEdit.setObjectName("client_fathername_add_LineEdit")
        self.client_fathername_add_LineEdit.textChanged.connect(counter_cl_fathername_letters)
        self.gridLayout_8.addWidget(self.client_fathername_add_LineEdit, 1, 0, 1, 1)
        self.client_fathername_add_Label = QtWidgets.QLabel(self.client_fathername_add_Frame)
        self.client_fathername_add_Label.setMinimumSize(QtCore.QSize(0, 20))
        self.client_fathername_add_Label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.client_fathername_add_Label.setObjectName("client_fathername_add_Label")
        self.client_fathername_add_Label.setText("Отчество")
        self.gridLayout_8.addWidget(self.client_fathername_add_Label, 0, 0, 1, 1)
        self.client_fathername_letter_num_Label = QtWidgets.QLabel(self.client_fathername_add_Frame)
        self.client_fathername_letter_num_Label.setMinimumSize(QtCore.QSize(40, 30))
        self.client_fathername_letter_num_Label.setMaximumSize(QtCore.QSize(40, 30))
        self.client_fathername_letter_num_Label.setObjectName("client_fathername_letter_num_Label")
        self.client_fathername_letter_num_Label.setText("0")
        self.gridLayout_8.addWidget(self.client_fathername_letter_num_Label, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.client_fathername_add_Frame, 2, 0, 1, 1)
        self.search_btn_Frame = QtWidgets.QFrame(self.user_info_Frame)
        self.search_btn_Frame.setMinimumSize(QtCore.QSize(0, 0))
        self.search_btn_Frame.setMaximumSize(QtCore.QSize(570, 63))
        self.search_btn_Frame.setObjectName("search_btn_Frame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.search_btn_Frame)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setHorizontalSpacing(5)
        self.gridLayout_10.setVerticalSpacing(2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.search_Btn = QtWidgets.QPushButton(self.search_btn_Frame)
        self.search_Btn.setMinimumSize(QtCore.QSize(0, 30))
        self.search_Btn.setMaximumSize(QtCore.QSize(500, 16777215))
        self.search_Btn.setObjectName("search_Btn")
        self.search_Btn.setText("Найти")
        self.search_Btn.clicked.connect(ClickSearch)
        self.gridLayout_10.addWidget(self.search_Btn, 0, 0, 1, 1)
        self.search_btn_FrameSpacer = QtWidgets.QFrame(self.search_btn_Frame)
        self.search_btn_FrameSpacer.setMinimumSize(QtCore.QSize(40, 30))
        self.search_btn_FrameSpacer.setMaximumSize(QtCore.QSize(40, 30))
        self.search_btn_FrameSpacer.setObjectName("search_btn_FrameSpacer")
        self.gridLayout_10.addWidget(self.search_btn_FrameSpacer, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.search_btn_Frame, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.user_info_Frame)
        self.search_resault_Frame = QtWidgets.QFrame(self.tab)
        self.search_resault_Frame.setObjectName("search_resault_Frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.search_resault_Frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.client_search_info_Frame = QtWidgets.QFrame(self.search_resault_Frame)
        self.client_search_info_Frame.setMinimumSize(QtCore.QSize(400, 100))
        self.client_search_info_Frame.setMaximumSize(QtCore.QSize(805, 80))
        self.client_search_info_Frame.setObjectName("client_search_info_Frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.client_search_info_Frame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cl_activities_num_Label = QtWidgets.QLabel(self.client_search_info_Frame)
        self.cl_activities_num_Label.setMaximumSize(QtCore.QSize(100, 33))
        self.cl_activities_num_Label.setTextFormat(QtCore.Qt.AutoText)
        self.cl_activities_num_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.cl_activities_num_Label.setObjectName("cl_activities_num_Label")
        self.cl_activities_num_Label.setText("Выды деят-ти")
        self.gridLayout_4.addWidget(self.cl_activities_num_Label, 3, 3, 1, 1)
        self.cl_found_name_LineEdit = QtWidgets.QLineEdit(self.client_search_info_Frame)
        self.cl_found_name_LineEdit.setMinimumSize(QtCore.QSize(150, 30))
        self.cl_found_name_LineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cl_found_name_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cl_found_name_LineEdit.setReadOnly(True)
        self.cl_found_name_LineEdit.setObjectName("cl_found_name_LineEdit")
        self.gridLayout_4.addWidget(self.cl_found_name_LineEdit, 4, 0, 1, 1)
        self.cl_found_fathername_LineEdit = QtWidgets.QLineEdit(self.client_search_info_Frame)
        self.cl_found_fathername_LineEdit.setMinimumSize(QtCore.QSize(150, 30))
        self.cl_found_fathername_LineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cl_found_fathername_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cl_found_fathername_LineEdit.setReadOnly(True)
        self.cl_found_fathername_LineEdit.setObjectName("cl_found_fathername_LineEdit")
        self.gridLayout_4.addWidget(self.cl_found_fathername_LineEdit, 4, 2, 1, 1)
        self.cl_found_name_Label = QtWidgets.QLabel(self.client_search_info_Frame)
        self.cl_found_name_Label.setMaximumSize(QtCore.QSize(16777215, 33))
        self.cl_found_name_Label.setTextFormat(QtCore.Qt.AutoText)
        self.cl_found_name_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.cl_found_name_Label.setObjectName("cl_found_name_Label")
        self.cl_found_name_Label.setText("Имя")
        self.gridLayout_4.addWidget(self.cl_found_name_Label, 3, 0, 1, 1)
        self.cl_found_secname_LineEdit = QtWidgets.QLineEdit(self.client_search_info_Frame)
        self.cl_found_secname_LineEdit.setMinimumSize(QtCore.QSize(150, 30))
        self.cl_found_secname_LineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cl_found_secname_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cl_found_secname_LineEdit.setReadOnly(True)
        self.cl_found_secname_LineEdit.setObjectName("cl_found_secname_LineEdit")
        self.gridLayout_4.addWidget(self.cl_found_secname_LineEdit, 4, 1, 1, 1)
        self.cl_activities_num_LineEdit = QtWidgets.QLineEdit(self.client_search_info_Frame)
        self.cl_activities_num_LineEdit.setMinimumSize(QtCore.QSize(100, 30))
        self.cl_activities_num_LineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cl_activities_num_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cl_activities_num_LineEdit.setReadOnly(True)
        self.cl_activities_num_LineEdit.setObjectName("cl_activities_num_LineEdit")
        self.gridLayout_4.addWidget(self.cl_activities_num_LineEdit, 4, 3, 1, 1)
        self.cl_found_secname_Label = QtWidgets.QLabel(self.client_search_info_Frame)
        self.cl_found_secname_Label.setMaximumSize(QtCore.QSize(16777215, 33))
        self.cl_found_secname_Label.setTextFormat(QtCore.Qt.AutoText)
        self.cl_found_secname_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.cl_found_secname_Label.setObjectName("cl_found_secname_Label")
        self.cl_found_secname_Label.setText("Фамилия")
        self.gridLayout_4.addWidget(self.cl_found_secname_Label, 3, 1, 1, 1)
        self.cl_found_fathername_Label = QtWidgets.QLabel(self.client_search_info_Frame)
        self.cl_found_fathername_Label.setMaximumSize(QtCore.QSize(16777215, 33))
        self.cl_found_fathername_Label.setTextFormat(QtCore.Qt.AutoText)
        self.cl_found_fathername_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.cl_found_fathername_Label.setObjectName("cl_found_fathername_Label")
        self.cl_found_fathername_Label.setText("Отчество")
        self.gridLayout_4.addWidget(self.cl_found_fathername_Label, 3, 2, 1, 1)
        self.horizontalLayout_9.addWidget(self.client_search_info_Frame)
        self.verticalLayout_2.addWidget(self.search_resault_Frame)
        self.client_activities_info_Frame = QtWidgets.QFrame(self.tab)
        self.client_activities_info_Frame.setMinimumSize(QtCore.QSize(0, 223))
        self.client_activities_info_Frame.setObjectName("client_activities_info_Frame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.client_activities_info_Frame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        # ScrollArea
        self.activity_ScrollArea = QtWidgets.QScrollArea(self.client_activities_info_Frame)
        self.activity_ScrollArea.setMinimumSize(QtCore.QSize(0, 80))
        self.activity_ScrollArea.setWidgetResizable(True)
        self.activity_ScrollArea.setObjectName("activity_ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 939, 166))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.scroll_area_title_Label = QtWidgets.QLabel(self.client_activities_info_Frame)
        self.scroll_area_title_Label.setMinimumSize(QtCore.QSize(0, 30))
        self.scroll_area_title_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.scroll_area_title_Label.setObjectName("scroll_area_title_Label")
        self.scroll_area_title_Label.setText("Виды деятельности")
        self.gridLayout_9.addWidget(self.scroll_area_title_Label, 0, 0, 1, 5)
        self.activite_name_Label = QtWidgets.QLabel(self.client_activities_info_Frame)
        self.activite_name_Label.setMinimumSize(QtCore.QSize(0, 30))
        self.activite_name_Label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.activite_name_Label.setTextFormat(QtCore.Qt.AutoText)
        self.activite_name_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.activite_name_Label.setObjectName("activite_name_Label")
        self.activite_name_Label.setText("Наименование")
        self.gridLayout_9.addWidget(self.activite_name_Label, 1, 0, 1, 1)
        self.activite_tax_Label = QtWidgets.QLabel(self.client_activities_info_Frame)
        self.activite_tax_Label.setMinimumSize(QtCore.QSize(0, 30))
        self.activite_tax_Label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.activite_tax_Label.setTextFormat(QtCore.Qt.AutoText)
        self.activite_tax_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.activite_tax_Label.setObjectName("activite_tax_Label")
        self.activite_tax_Label.setText("Налог")
        self.gridLayout_9.addWidget(self.activite_tax_Label, 1, 1, 1, 1)
        self.delete_activity_Label = QtWidgets.QLabel(self.client_activities_info_Frame)
        self.delete_activity_Label.setMinimumSize(QtCore.QSize(0, 30))
        self.delete_activity_Label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.delete_activity_Label.setTextFormat(QtCore.Qt.AutoText)
        self.delete_activity_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.delete_activity_Label.setObjectName("delete_activity_Label")
        self.delete_activity_Label.setText("Удалить")
        self.gridLayout_9.addWidget(self.delete_activity_Label, 1, 4, 1, 1)
        self.activite_penalty_Label = QtWidgets.QLabel(self.client_activities_info_Frame)
        self.activite_penalty_Label.setMinimumSize(QtCore.QSize(0, 30))
        self.activite_penalty_Label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.activite_penalty_Label.setTextFormat(QtCore.Qt.AutoText)
        self.activite_penalty_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.activite_penalty_Label.setObjectName("activite_penalty_Label")
        self.activite_penalty_Label.setText("Пеня")
        self.gridLayout_9.addWidget(self.activite_penalty_Label, 1, 2, 1, 1)
        self.activite_city_Label = QtWidgets.QLabel(self.client_activities_info_Frame)
        self.activite_city_Label.setMinimumSize(QtCore.QSize(0, 30))
        self.activite_city_Label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.activite_city_Label.setTextFormat(QtCore.Qt.AutoText)
        self.activite_city_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.activite_city_Label.setObjectName("activite_city_Label")
        self.activite_city_Label.setText("Город")
        self.gridLayout_9.addWidget(self.activite_city_Label, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.client_activities_info_Frame)

        self.activity_ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_9.addWidget(self.activity_ScrollArea, 2, 0, 1, 5)
        self.close_tab_Frame = QtWidgets.QFrame(self.tab)
        self.close_tab_Frame.setMinimumSize(QtCore.QSize(400, 50))
        self.close_tab_Frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.close_tab_Frame.setObjectName("close_tab_Frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.close_tab_Frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.close_tab_FrameSpacer = QtWidgets.QFrame(self.close_tab_Frame)
        self.close_tab_FrameSpacer.setObjectName("close_tab_FrameSpacer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.close_tab_FrameSpacer)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4.addWidget(self.close_tab_FrameSpacer)
        self.close_tab_btn_Frame = QtWidgets.QFrame(self.close_tab_Frame)
        self.close_tab_btn_Frame.setMinimumSize(QtCore.QSize(250, 50))
        self.close_tab_btn_Frame.setMaximumSize(QtCore.QSize(300, 50))
        self.close_tab_btn_Frame.setObjectName("close_tab_btn_Frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.close_tab_btn_Frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.close_tab_Btn = QtWidgets.QPushButton(self.close_tab_btn_Frame)
        self.close_tab_Btn.setMinimumSize(QtCore.QSize(0, 30))
        self.close_tab_Btn.setObjectName("close_tab_Btn")
        self.close_tab_Btn.setText("Готово")
        self.close_tab_Btn.clicked.connect(clickCloseTab)
        self.horizontalLayout_3.addWidget(self.close_tab_Btn)
        self.horizontalLayout_4.addWidget(self.close_tab_btn_Frame)
        self.verticalLayout_2.addWidget(self.close_tab_Frame)

        return self.tab
